Major upgrade
- YunoHost 2.4
- Remove method, port, host and fork (remote installs should be done
with direct_ynh) for simplicity
- YunoHost multimedia folder structure
- Integrates with transmission (RPC or watchdir, if available)
- Systemd instead of init
- Backup/restore
- Automatic port finding

Because these are major changes, I was not able to manage upgrade from
previous versions. You must remove the app and reinstall.

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,62 +1,54 @@
 #!/bin/bash
 
-#debug commands
-#exec > >(tee /tmp/debug-install.log)
-#exec 2>&1
+	set -eu
+	app=$YNH_APP_INSTANCE_NAME
+	source="https://github.com/CouchPotato/CouchPotatoServer"
+
+
+# Source app helpers
+. /usr/share/yunohost/helpers
 
 # Retrieve arguments
-app_domain=$1
-app_path=$2
-app_public=$3
-app_method=$4
-app_port=$5
-app_fork=$6
-app_host=$7
+	domain=$YNH_APP_ARG_DOMAIN
+	path=$YNH_APP_ARG_PATH
 
-# Basic variable declaration
-BASEDIR="$(dirname "$(pwd)")"
-
-# Common variable declaration
-app_id=couchpotato
-app_user=couchpotato
-app_local_host="127.0.0.1"
-app_python_bin="/usr/bin/python"
-## Destinations definitions
-app_install_dir="/opt/yunohost/${app_id}"
-app_data_dir="/home/yunohost.app/${app_id}"
-app_logs_dir="/var/log/${app_id}"
-app_config_file="${app_data_dir}/settings.conf"
-app_pid_file="/var/run/${app_id}/${app_id}.pid"
-## Sources definitions
-app_src_conf="$BASEDIR/conf/${app_id}.conf"
-app_src_dfts="$BASEDIR/conf/${app_id}.defaults"
-app_src_init="$BASEDIR/conf/${app_id}.init"
-app_src_nginx_conf="$BASEDIR/conf/nginx.conf"
-
+# Correct path: puts a / at the start and nothing at the end
+	if [ "${path:0:1}" != "/" ]; then
+		path="/$path"
+	fi
+	if [ "${path:${#path}-1}" == "/" ] && [ ${#path} -gt 1 ]; then
+		path="${path:0:${#path}-1}"
+	fi
 
 # Check domain/path availability
-sudo yunohost app checkurl $app_domain$app_path -a $app_id
-if [[ ! $? -eq 0 ]]; then
-	exit 1
-fi
+	sudo yunohost app checkurl "${domain}${path}" -a "$app" \
+		|| ynh_die "Path not available: ${domain}${path}"
 
+# Destinations definitions
+	app_install_dir="/opt/yunohost/$app"
+	app_data_dir="/home/yunohost.app/$app"
+	app_logs_dir="/var/log/$app"
+	app_config_file="${app_data_dir}/settings.conf"
+	app_pid_file="/var/run/$app/$app.pid"
+	app_python_bin="/usr/bin/python"
 
-# Make install if localhost installation
-if [[ $app_method == "LOCAL"* ]]; then
+# Install Couchpotato
 
-	# Check port availability
-	sudo yunohost app checkport $app_port
-	if [[ ! $? -eq 0 ]]; then
-		exit 1
-	fi
+	# Get first available port
+	port=5050
+	sudo yunohost app checkport $port
+	while [[ ! $? -eq 0 ]]; do
+		port=$((port+1))
+		sudo yunohost app checkport $port
+	done
+	ynh_app_setting_set "$app" port "$port"
 	
 	# Make directories
 	sudo mkdir -p $app_data_dir
 	sudo mkdir -p $app_install_dir
 	
 	# Install latest version of app using the fork
-	sudo apt-get install -y git-core
-	sudo git clone $app_fork $app_install_dir
+	sudo git clone $source $app_install_dir
 	
 	# Install dependencies (using virtualenv)
 	if [[ $(python --version 2>&1) != Python\ 2* ]]; then
@@ -67,73 +59,98 @@ if [[ $app_method == "LOCAL"* ]]; then
 	fi
 	
 	# Create app user
-	id -u $app_user &>/dev/null || sudo useradd --home-dir $app_install_dir --shell /bin/false $app_user
-	
-	# Configure daemon
-	sudo sed -i "s@USERTOCHANGE@$app_user@g" $app_src_dfts
-	sudo sed -i "s@APPDIRTOCHANGE@$app_install_dir@g" $app_src_dfts
-	sudo sed -i "s@DATADIRTOCHANGE@$app_data_dir@g" $app_src_dfts
-	sudo sed -i "s@PIDFILETOCHANGE@$app_pid_file@g" $app_src_dfts
-	sudo sed -i "s@PYTBINTOCHANGE@$app_python_bin@g" $app_src_dfts
-	sudo sed -i "s@OPTSTOCHANGE@$app_config_file@g" $app_src_dfts
-	sudo cp -a $app_src_dfts /etc/default/$app_id
-	sudo cp -a $app_src_init /etc/init.d/$app_id
-	
+	id -u $app &>/dev/null || sudo useradd --home-dir $app_install_dir --shell /bin/false $app
+
+	# YunoHost multimedia
+		# Add yunohost.multimedia directory
+		wget -qq https://github.com/YunoHost-Apps/yunohost.multimedia/archive/master.zip
+		unzip -qq master.zip
+		sudo ./yunohost.multimedia-master/script/ynh_media_build.sh
+		# Give write access to the yunohost.multimedia directory so that Couchpotato can move Movies to the Movie directory
+		sudo usermod -a -G multimedia $app
+		# Creates the "Movies" subfolder in "Video"
+		sudo mkdir -p "/home/yunohost.multimedia/share/Video/Movies"
+		# Fix permissions
+		sudo ./yunohost.multimedia-master/script/ynh_media_build.sh
+
+	# Transmission link: Preferred method is direct RPC link. If not available, switch to watchdir.
+	transmission_rpcurl=""
+	transmission_rpcpassword=""
+	transmission_watchdir=""
+	# Check if Transmission is installed
+	if [[ -z $(sudo yunohost app list -i -f transmission | grep -v 'apps:') ]]; then
+		sudo sed -i "s@__RPC__@0@g"			../conf/couchpotato.conf	# Disable Transmission RPC
+		sudo sed -i "s@__BLACKHOLE__@0@g"	../conf/couchpotato.conf	# Disable Transmission Watchdir
+		sudo sed -i "s@__RENAMER__@0@g"		../conf/couchpotato.conf	# Disable Renamer
+	else
+		echo "Transmission is installed. Trying to link it to CouchPotato..."
+		# Check if the transmission password is in settings
+		if [[ -n $(ynh_app_setting_get transmission rpcpassword || true) ]]; then
+			echo "Transmission will be linked to CouchPotato directly"
+			transmission_rpcurl="$(ynh_app_setting_get transmission path)transmission"
+			transmission_rpcpassword=$(ynh_app_setting_get transmission rpcpassword)
+			sudo sed -i "s@__RPC__@1@g"			../conf/couchpotato.conf	# Enable Transmission RPC
+			sudo sed -i "s@__BLACKHOLE__@0@g"	../conf/couchpotato.conf	# Disable Transmission Watchdir
+			sudo sed -i "s@__RENAMER__@1@g"		../conf/couchpotato.conf	# Enable Renamer
+			# If transmission uses YunoHost multimedia, use its folder for the renamer
+		else
+			# Check if transmission has watchdir enabled
+			if [[ -n $(ynh_app_setting_get transmission watchdir || true) ]]; then
+				echo "Transmission will be linked to CouchPotato with watchdir"
+				transmission_watchdir=$(ynh_app_setting_get transmission watchdir)
+				sudo sed -i "s@__RPC__@0@g"			../conf/couchpotato.conf	# Disable Transmission RPC
+				sudo sed -i "s@__BLACKHOLE__@1@g"	../conf/couchpotato.conf	# Enable Transmission Watchdir
+				sudo sed -i "s@__RENAMER__@1@g"		../conf/couchpotato.conf	# Enable Renamer	
+				# If transmission uses YunoHost multimedia, use its folder for the renamer		
+			else
+				echo "Cannot link Couchpotato to Transmission because Transmission has no RPC password or watchdir available."
+				sudo sed -i "s@__RPC__@0@g"			../conf/couchpotato.conf	# Disable Transmission RPC
+				sudo sed -i "s@__BLACKHOLE__@0@g"	../conf/couchpotato.conf	# Disable Transmission Watchdir
+				sudo sed -i "s@__RENAMER__@0@g"		../conf/couchpotato.conf	# Disable Renamer
+			fi
+		fi
+	fi
+
 	# Configure App
-	sudo sed -i "s@PATHTOCHANGE@$app_path@g" $app_src_conf
-	sudo sed -i "s@PORTTOCHANGE@$app_port@g" $app_src_conf
-	sudo sed -i "s@DATADIRTOCHANGE@$app_data_dir@g" $app_src_conf
-	sudo cp -a $app_src_conf $app_config_file
+	sudo sed -i "s@__RPCURL__@$transmission_rpcurl@g" 			../conf/couchpotato.conf
+	sudo sed -i "s@__RPCPASSWORD__@$transmission_rpcpassword@g" ../conf/couchpotato.conf
+	sudo sed -i "s@__WATCHDIR__@$transmission_watchdir@g" 		../conf/couchpotato.conf
+
+	sudo sed -i "s@__PATH__@$path@g" 							../conf/couchpotato.conf
+	sudo sed -i "s@__PORT__@$port@g" 							../conf/couchpotato.conf
+	sudo sed -i "s@__DATADIR__@$app_data_dir@g" 				../conf/couchpotato.conf
+
+	sudo cp -a ../conf/couchpotato.conf $app_config_file
 	
 	# Redirect logs directory
-	if [[ $app_logs_dir != "$app_data_dir"* ]]; then
-		sudo mkdir -p $app_logs_dir
-		sudo chown -R $app_user $app_logs_dir
-		sudo chmod +x -R $app_logs_dir
-		sudo sed -i "s@self.log_dir =.*@self.log_dir = '$app_logs_dir'@g" $app_install_dir/CouchPotato.py
-	fi
+	sudo mkdir -p $app_logs_dir
+	sudo chown -R $app $app_logs_dir
+	sudo chmod +x -R $app_logs_dir
+	sudo sed -i "s@self.log_dir =.*@self.log_dir = '$app_logs_dir'@g" $app_install_dir/CouchPotato.py
+
+	# Permissions
+	sudo chown -R $app:$app $app_install_dir
+	sudo chown -R $app:$app $app_data_dir
 	
-	# Set rights
-	sudo chown -R $app_user $app_install_dir
-	sudo chown -R $app_user $app_data_dir
-	sudo chmod +x /etc/init.d/$app_id
-	sudo chmod +x -R $app_install_dir
-	sudo chmod +x -R $app_data_dir
-	
-	# Add service to YunoHost's monitoring
-	sudo yunohost service add $app_id --log $app_logs_dir --status "ps aux | grep $app_id | grep -v grep"
-	
-	# Start daemon at boot
-	sudo update-rc.d $app_id defaults
-	
+	# Configure service
+	sed -i "s@__PYTHON__@$app_python_bin@g" 		../conf/systemd.service
+	sed -i "s@__APPDIR__@$app_install_dir@g" 		../conf/systemd.service
+	sed -i "s@__DATADIR__@$app_data_dir@g" 			../conf/systemd.service
+	sed -i "s@__PIDFILE__@$app_pid_file@g" 			../conf/systemd.service
+	sed -i "s@__CONFIGFILE__@$app_config_file@g" 	../conf/systemd.service
+	sed -i "s@__USER__@$app@g" 						../conf/systemd.service
+	sudo cp ../conf/systemd.service /etc/systemd/system/$app.service
+	sudo systemctl daemon-reload
+	sudo systemctl enable $app
+	sudo yunohost service add $app
+
 	# Start service
-	sudo service $app_id start
-	
-	# Set proxy host variable
-	app_host="http://${app_local_host}:${app_port}${app_path%/}"
-	
-fi
+	sudo yunohost service start $app
 
-
-# Remove trailing "/" for next commands
-app_path=${app_path%/}
-
-# Configure Nginx 
-sudo sed -i "s@PATHTOCHANGE@$app_path@g" $app_src_nginx_conf
-sudo sed -i "s@HOSTTOCHANGE@$app_host@g" $app_src_nginx_conf
-sudo cp $app_src_nginx_conf /etc/nginx/conf.d/$app_domain.d/$app_id.conf
-
-# If app is public, add url to SSOWat conf as skipped_uris
-if [[ $app_public == "Yes" ]]; then
-	# unprotected_uris allows SSO credentials to be passed anyway.
-	sudo yunohost app setting $app_id unprotected_uris -v "/"
-fi
-	
-# Save app settings
-sudo yunohost app setting $app_id public -v "$app_public"
-sudo yunohost app setting $app_id method -v "$app_method"
-sudo yunohost app setting $app_id host -v "$app_host"
+# Configure Nginx and reload
+	sed -i "s@__PATH__@$path@g" ../conf/nginx.conf
+	sed -i "s@__PORT__@$port@g" ../conf/nginx.conf
+	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
 
 # Reload Nginx and regenerate SSOwat conf
-sudo service nginx reload
-sudo yunohost app ssowatconf
+	sudo service nginx reload
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,75 +1,100 @@
 #!/bin/bash
+	app=$YNH_APP_INSTANCE_NAME
+	source="https://github.com/CouchPotato/CouchPotatoServer"
 
-# Basic variable declaration
-BASEDIR="$(dirname "$(pwd)")"
+# Backup the current version of the app, restore it if the upgrade fails
+	EXIT_PROPERLY () {
+		trap '' EXIT
+		set +e
+		sudo yunohost backup restore --ignore-hooks $app-before-upgrade --apps $app --force --quiet	# Restore the backup if upgrade failed
+		ynh_die "Upgrade failed. The app was restored to the way it was before the failed upgrade."
+	}
+	if [[ -n $(sudo yunohost backup info $app-before-upgrade || true) ]]; then
+		sudo yunohost backup delete $app-before-upgrade
+	fi
+	sudo yunohost backup create --ignore-hooks --apps $app --name $app-before-upgrade --quiet
+	set -e
+	trap EXIT_PROPERLY ERR
 
-# Common variable declaration
-app_id=couchpotato
-app_user=couchpotato
-app_install_dir="/opt/yunohost/${app_id}"
-app_data_dir="/home/yunohost.app/${app_id}"
-app_logs_dir="/var/log/${app_id}"
-## Sources definitions
-app_src_init="$BASEDIR/conf/${app_id}.init"
-app_src_nginx_conf="$BASEDIR/conf/nginx.conf"
+# Source app helpers
+. /usr/share/yunohost/helpers
 
 # Retrieve arguments
-app_public="$(sudo yunohost app setting ${app_id} public)"
-app_method="$(sudo yunohost app setting ${app_id} method)"
-app_domain="$(sudo yunohost app setting ${app_id} domain)"
-app_path="$(sudo yunohost app setting ${app_id} path)"
-app_host="$(sudo yunohost app setting ${app_id} host)"
+	domain=$(ynh_app_setting_get "$app" domain)
+	path=$(ynh_app_setting_get "$app" path)
+	port=$(ynh_app_setting_get "$app" port)
 
+# Cancel upgrade if the version is too old
+	if [[ -n $(ynh_app_setting_get $app method) ]]; then
+		ynh_die "Your current version is too old and cannot be upgraded.\
+		If you had a local install, please remove the app and reinstall it.\
+		If you had a remote install, please remove the app and install redirect_ynh for this purpose instead."	
+	fi
 
-# Make upgrade if localhost installation
-if [[ $app_method == "LOCAL"* ]]; then
+# Destinations definitions
+	app_install_dir="/opt/yunohost/$app"
+	app_data_dir="/home/yunohost.app/$app"
+	app_logs_dir="/var/log/$app"
+	app_config_file="${app_data_dir}/settings.conf"
+	app_pid_file="/var/run/$app/$app.pid"
+	app_python_bin="/usr/bin/python"
+
+# Upgrade Couchpotato
 
 	# Kill app
-	sudo service $app_id stop
-	sudo killall $app_id
-	
+	sudo service $app stop || true
+
 	# Upgrade to the latest version of app using the fork
 	cd $app_install_dir && sudo git pull
 	cd -
-
-	# Upgrade dependencies
 	
+	# Upgrade dependencies
+	if [[ $(python --version 2>&1) != Python\ 2* ]]; then
+		app_python_bin=$app_install_dir/bin/python
+		sudo apt-get install -y python-pip python-virtualenv python-dev uwsgi uwsgi-plugin-python
+	fi
+
+	# YunoHost multimedia
+		# Add yunohost.multimedia directory
+		wget -qq https://github.com/YunoHost-Apps/yunohost.multimedia/archive/master.zip
+		unzip -qq master.zip
+		sudo ./yunohost.multimedia-master/script/ynh_media_build.sh
+		# Give write access to the yunohost.multimedia directory so that Couchpotato can move Movies to the Movie directory
+		sudo usermod -a -G multimedia $app
+		# Creates the "Movies" subfolder in "Video"
+		sudo mkdir -p "/home/yunohost.multimedia/share/Video/Movies"
+		# Fix permissions
+		sudo ./yunohost.multimedia-master/script/ynh_media_build.sh
+
+
 	# Redirect logs directory
 	if [[ $app_logs_dir != "$app_data_dir"* ]]; then
 		sudo sed -i "s@self.log_dir =.*@self.log_dir = '$app_logs_dir'@g" $app_install_dir/CouchPotato.py
 	fi
+
+	# Permissions
+	sudo chown -R $app:$app $app_install_dir
+	sudo chown -R $app:$app $app_data_dir
 	
-	# Update init file
-	sudo cp -a $app_src_init /etc/init.d/$app_id
-	
-	# Set rights
-	sudo chown -R $app_user $app_install_dir
-	sudo chmod +x /etc/init.d/$app_id
-	sudo chmod +x -R $app_install_dir
-	
+	# Configure service
+	sed -i "s@__PYTHON__@$app_python_bin@g" 		../conf/systemd.service
+	sed -i "s@__APPDIR__@$app_install_dir@g" 		../conf/systemd.service
+	sed -i "s@__DATADIR__@$app_data_dir@g" 			../conf/systemd.service
+	sed -i "s@__PIDFILE__@$app_pid_file@g" 			../conf/systemd.service
+	sed -i "s@__CONFIGFILE__@$app_config_file@g" 	../conf/systemd.service
+	sed -i "s@__USER__@$app@g" 						../conf/systemd.service
+	sudo cp ../conf/systemd.service /etc/systemd/system/$app.service
+	sudo systemctl daemon-reload
+	sudo systemctl enable $app
+	sudo yunohost service add $app
+
 	# Start service
-	sudo service $app_id start
-	
-fi
+	sudo yunohost service start $app
 
-
-# Remove trailing "/" for next commands
-app_path=${app_path%/}
-
-# Configure Nginx 
-sudo sed -i "s@PATHTOCHANGE@$app_path@g" $app_src_nginx_conf
-sudo sed -i "s@HOSTTOCHANGE@$app_host@g" $app_src_nginx_conf
-sudo cp $app_src_nginx_conf /etc/nginx/conf.d/$app_domain.d/$app_id.conf
-
-# If app is public, add url to SSOWat conf as skipped_uris
-if [[ $app_public = "Yes" ]];
-then
-	# See install script
-	sudo yunohost app setting $app_id unprotected_uris -v "/"
-	# Remove old settings
-	sudo yunohost app setting $app_id skipped_uris -d
-fi
+# Configure Nginx and reload
+	sed -i "s@__PATH__@$path@g" ../conf/nginx.conf
+	sed -i "s@__PORT__@$port@g" ../conf/nginx.conf
+	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
 
 # Reload Nginx and regenerate SSOwat conf
-sudo service nginx reload
-sudo yunohost app ssowatconf
+	sudo service nginx reload
